version: '3'

services:
  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:amd
    ports:
      - "8082:8080"
    environment:
      AUTH_TOKEN_LIFETIME: 1000
    platform: linux/arm64/v8